# In this file we are gonna learn about Pandas

# Pandas in the best too to do data analysis in python

In [3]:
import pandas as pd 
import numpy as np

In [2]:
# CREATING DATA FRAME FROM AN ARRAY

In [11]:
# OPTION 1
#creating an array
data = np.array([[1,4], [2,5], [3,6], [4,8]])

#creating a dataframek
pd.DataFrame(data, index = ['row1', 'row2', 'row3', 'row4'],
            columns = ['col1', 'col2'])

      col1  col2
row1     1     4
row2     2     5
row3     3     6
row4     4     8

In [4]:
#OPTION2 - CREATING AN ARRAY WITH LSIT FRAME (WITHOUT USING numpy)

data = [[1,4], [2,5], [3,6], [4,8]]
df = pd.DataFrame(data, index = ['row1', 'row2', 'row3', 'row4'],
            columns = ['col1', 'col2'])
df

      col1  col2
row1     1     4
row2     2     5
row3     3     6
row4     4     8

In [19]:
# OPTION3 - CREATING A DATA FRAME USING DICT

#list used for this exmaple 
states = ['California', 'Texas', 'Florida', 'New York']
population = [353264566, 54236265, 3256464, 53626545]

#storing list with in dict 
dct_states = {"States" : states , "Population": population}

#creating the data frame 
df_pop = pd.DataFrame(dct_states)
df_pop

       States  Population
0  California   353264566
1       Texas    54236265
2     Florida     3256464
3    New York    53626545

In [8]:
#CREATING DATA FRAME FROM A CSV FILE 

df_exams = pd.read_csv('../data/StudentsPerformance.csv')

# df_exams.head(10) #-- for first 5 data sets  argument passed to get the number of rows wanted

# df_exams #--to show complete summary of the data set 

# df_exams.tail() #--to show the last five rows of the data frame 

# df_exams.shape #-- to get the number of rows and column

# pd.set_option("display.max_rows",1000) #-- to only get the rows from the data frame 
# df_exams

In [24]:
# SOME BASICS ATTRIBUTE FUNCTION AND METHODS 

# df_exams.index #-- getting the index of the data frame 

# df_exams.columns #-- to get the names of the columns in the data frame 

# df_exams.dtypes #-- to get the type of data in columns of the data frame 

# df_exams.describe()  #-- shwoing the basics statictics of the data frame 

# len(df_exams) #-- to obtain the length of the data frame 

# max(df_exams) #-- get the highest index of the data frame 

# min(df_exams) #--get the lowest index of the dataframe 

# min(df_exams.index) #-- get the lowest index of the dataframe 

# type(df_exams) #-- get the type of the dataframe 

# round(df_exams) #-- round the values of the data frame

In [33]:
# SELECTING COLUMN IN DATAFRAME 

#Preferred way to select a column
# df_exams['gender']

#Check out the data type of the column
# type(df_exams['gender'])

#Series: attributes and methods
# df_exams['gender'].index
# df_exams['gender'].head

#Selecting a column with the dot sign (pitfalls)
# df_exams.gender

In [37]:
#HOW TO SELECT 2 OR MORE COLUMNS IN DATA FRAME [[]]

df_exams[['gender', 'math score']] #-- getting the gender and math score columns
type(df_exams[['gender', 'math score']]) #-- getting the type of the data frame

pandas.core.frame.DataFrame

In [40]:
# DIFFERENT WAYS TO ADD COLUMNS IN THE DATA FRAME 

# df_exams['language score'] = 70 #-- creating new column with the value 70 to each one of them 
# df_exams

In [61]:
# ADDING A NEW COLUMN WITH AN ARRAY
# import numpy as np

# # language_score = np.arange(0, 1000) #-- Creating an array with 1000 elements 

# # len(language_score) #-- getting the length of the element 

# df_exams['language score'] = language_score #-- add the new element language score as an column to the dataframe 

# df_exams

In [64]:
#CREATING A RANDOM INTEGER NUMBER BETWEEN 1 TO 100

# random_lan_num = np.random.randint(1, 100, size = 1000) #--random int marks 
# df_exams['language score'] = random_lan_num
# df_exams = df_exams.drop(columns=['language_score'])

# df_exams

In [70]:
#CREATING RANDOM FLOAT NUMBER BETWEENk 1 TO 100

# random_lan_float = np.random.uniform(1.1, 99.9, size = 1000) #-- random float marks 
# df_exams['language score'] = random_lan_float
# df_exams

In [12]:
# OPERATIONS WHICH WE CAN PERFORM ON DATAFRAMES --ROWS

# CALCULATING THE SUM IN ROW

# df_exams['math score'] + df_exams['reading score'] +  df_exams['writing score'] 

# #CALCULATING THE AVERAGE SCORE AND ASSIGNING THE RESULT TO A NEW COLUMN

# df_exams['average'] = (df_exams['math score'] + df_exams['reading score'] +  df_exams['writing score']) / 3
# df_exams

In [81]:
# OPERATIONS WHICH WE CAN PERFORM ON DATAFRAMES --COLUMNS

# **MATH OPERATIONS**

# df_exams['math score'].sum() #-- how to calculate the total sum

#-- count mean, std, max and min

# df_exams['math score'].count() 
# df_exams['math score'].mean()
# df_exams['math score'].std() 
# df_exams['math score'].max()
# df_exams['math score'].min()

#EASIER CALCULATION WITH DESCRIBE

df_exams.describe()

       math score  reading score  writing score  language score
count  1000.00000    1000.000000    1000.000000     1000.000000
mean     66.08900      69.169000      68.054000       50.193434
std      15.16308      14.600192      15.195657       28.170462
min       0.00000      17.000000      10.000000        1.142099
25%      57.00000      59.000000      57.750000       25.986430
50%      66.00000      70.000000      69.000000       49.535486
75%      77.00000      79.000000      79.000000       74.507502
max     100.00000     100.000000     100.000000       99.751954

In [73]:
# # ADDING A NEW/MULIPLE  COLUMN WITH THE ASSIGN OPERATOR 

# import numpy as np
 
# score1 = np.random.randint(1, 100, size = 1000) # -- Creating random number for new score column
# score2 = np.random.randint(1, 100, size = 1000)

# series1 = pd.Series(score1, index = np.arange(0, 1000)) #-- Creating a sereis using a random number 
# series2 = pd.Series(score2, index = np.arange(0, 1000))

# df_exams.assign(score1 = series1, score2 = series2) #-- Assigning the new columsn to the random number

#ADDING VALUE COUNT IN DATAFRAME

In [15]:
#VALUE COUNT IN DATAFRAME 

# #COUNTING GENEDER ELEMENT 

# len(df_exams['gender'])
# df_exams['gender'].count()

#To know number of male and female people in tha dataframe 

# df_exams['gender'].value_counts()


#Count element by category 

# df_exams['parental level of education'].value_counts()

#Return the relative frequency and round to 2 decimals places 
df_exams['parental level of education'].value_counts(normalize = True)

parental level of education
some college          0.226
associate's degree    0.222
high school           0.196
some high school      0.179
bachelor's degree     0.118
master's degree       0.059
Name: proportion, dtype: float64

#HOW TO SORT A DATAFRAME

In [25]:
#Sort by one column -- these methods do not make changes in the main data frame 

# df_exams.sort_values(by='math score') #ascending default 

#Sort decending by one column

# df_exams.sort_values('math score', ascending = False)

#Sort decending by multiple column 

# df_exams.sort_values(['math score', 'reading score'], ascending = False, inplace = True) #-- Inplace default == false, which means do not update acutal data frame but work on the copy of the data frame 

#Sort decending with a key function 

df_exams.sort_values('race/ethnicity', ascending = True, key= lambda col:col.str.lower())

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
778,female,group A,some college,standard,completed,72,79,82
546,female,group A,some high school,standard,completed,92,100,97
820,female,group A,some high school,standard,completed,85,90,92
741,female,group A,associate's degree,free/reduced,none,37,57,56
305,male,group A,some college,standard,none,69,67,69
...,...,...,...,...,...,...,...,...
297,male,group E,associate's degree,standard,completed,71,74,68
293,female,group E,bachelor's degree,standard,none,65,73,75
289,male,group E,some high school,standard,completed,77,76,77
206,male,group E,bachelor's degree,standard,none,82,62,62
499,male,group E,some college,standard,none,76,71,72

# Create Index

In [26]:
import numpy as np
import random

In [37]:
#Creating non repetitive values for the index

new_index = np.arange(0, 1000)
# new_index

#Shuffling the index 
random.shuffle(new_index)

#Create a new column for the new_index
df_exams['new_index'] =  new_index
df_exams


#Set new_index column as index 
df_exams.set_index('new_index')

#Sort dataframe for new index 
df_exams.sort_index()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,new_index
0,female,group B,bachelor's degree,standard,none,72,72,74,761
1,female,group C,some college,standard,completed,69,90,88,941
2,female,group B,master's degree,standard,none,90,95,93,815
3,male,group A,associate's degree,free/reduced,none,47,57,44,128
4,male,group C,some college,standard,none,76,78,75,839
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,412
996,male,group C,high school,free/reduced,none,62,55,55,289
997,female,group C,high school,free/reduced,completed,59,71,65,526
998,female,group D,some college,standard,completed,68,78,77,108
999,female,group D,some college,free/reduced,none,77,86,86,193